### ISSUE TITLE
[ASTextNode] Truncation issue in text with lineSpacing

### ISSUE THREAD

**Issue by yxztj** [facebookarchive/AsyncDisplayKit#2105]
@hannahmbanana  Both latest master branch and 1.9.81 are tested.
Repro steps:
1. Create ASTextNode with maximumNumberOfLines of 3
2. Set attributedText with lineSpacing > 0 (won't repro if = 0)
3. Set truncation string with the same attributes
At last we would get **a wrong number of lines**.
I created a repo to demo: https://github.com/yxztj/ASTextNodeTest

**With ASDK master branch**(demo project branch "master"):
Expected:
<img width="318" alt="screen shot 2016-08-19 at 8 59 51 pm" src="https://cloud.githubusercontent.com/assets/3334458/17810625/d1b8d59c-6650-11e6-938a-2f6e7a3a9968.png">
Actual:
<img width="315" alt="screen shot 2016-08-19 at 8 59 24 pm" src="https://cloud.githubusercontent.com/assets/3334458/17810629/d4851880-6650-11e6-8f12-a90cbff3dce8.png">

**With ASDK 1.9.81**(demo project branch "1.9.81"):
At first number of lines are correct. But when scrolling down and up again(text node re-rendered), the issue appears just as in ASDK master branch above.
Please let me know if additional information is required.

**Comment by yxztj** [comment]
@maicki Since it's a production issue, resolving it is important to us. Do you think we can have a quick workaround?

**Comment by yxztj** [comment]
@appleguy Is there any updates on this issue？

**Comment by yxztj** [comment]
@appleguy After spending some time diving into ASTextKitRenderer, here's what I've found: 

Suppose we have 10 lines of text, 5px height for text and 2px lineSpacing, setting maximumNumberOfLines to 3. During the time, [ASTextKitRenderer _calculateSize] is called several times.
## First pass:
Creating [ASTextKitRenderer context] with unlimited constrainedSize in height.
Truncate textStorage into 3 lines. Set node's _calculatedSize height to the height of 3 lines, which is **19px**(5px * 3 + 2px * 2) 
## Second pass:
The context is re-created with constrained size with 19px height and original 10 lines of text.
Now the truncator uses 19px height in [layoutManager glyphRangeForBoundingRect]. This is enough for the text after truncation(3 lines of text), however the rect is not enough for clipping 10 lines of text into 3 lines, which is **21px** height(5 * 3 + 2 * 3, the lineSpacing after 3rd line is also counted. I'm not sure if it's by design in TextKit.) So we only got 2 lines finally.

Hope we can get a fix based on information above :)

**Comment by appleguy** [comment]
@yxztj great info, thanks!  The results above — were they tested with master, or 1.9.90?  Master does have some changes in this area.

The initial height calculation — is the value for the hight coming from TextKit?  I'm thinking it should return the necessary height to draw...if it is not, then this is a TextKit bug.  It is something we may should be able to work around, but this is a bit tricky, because the line spacing property could change in different ranges in the attributed string...and Apple may fix the sizing bug in a future iOS version.

If it's not a TextKit bug and is only an ASDK bug, that's certainly great news!

Relatedly, we currently have an ASTextKitRenderer caching mechanism in-place, but disabled.  It's intended that the second pass here not be necessary, and that would seemingly fix the issue too.  However we should make sure the result is consistently the same even if caching were to fix it, since a cache shouldn't be required for correctness.

Thanks again, looking forward to fixing this.  We made some key breakthroughs adopting the new layout API version in Pinterest today, and will be intensely focused on it this week, but the test case and debugging you provided will make it much more practical for me to try and fix it this weekend

**Comment by yxztj** [comment]
@appleguy Thanks for the reply. Now I found some more information. All test is based on latest master branch.

1. In ASTextNode calculateSizeThatFits, textRenderer is required to calculate its size. At this time constrainedSize height is infinite. 
2. After size is calculated(using [layoutManager usedRectForTextContainer]), in ASTextNode calculatedLayoutDidChange, it sets the result as new constrainedSize for renderer. Since the size is changed, textRenderer discard its context and reset all variables.
3. In ASTextNode drawRect, the renderer needs to re-calculate its size based on new constrainedSize, which is only enough for a total of 3 lines(2 lineSpacing count), but not good for clipping 10 lines to 3 with lineSpacing > 0, as the 3rd lineSpacing is also needed for TextKit to render the 3rd line. I'm not sure if this is by design.

So the problem could be that setting constrainedSize on the renderer leads to reseting its context, triggering another size calculation during drawRect. Due to short in height, truncation result is different than first pass. That is to say, if there's a third pass we will get another line missing..

Is it necessary to reset textRender's context on calculatedLayoutDidChange? Anyway its expensive for the text size to be calculate twice(in both layout and drawRect, even if with no truncation), as we already have the correct size for truncated text.

**Comment by yxztj** [comment]
OK I've submitted a bug to apple. It shouldn't be required to give space for lineSpacing below last line to get it rendered. But I doubt Apple is going to look at it soon..
Can we turn on textRenderer caching to work around this issue now?

**Comment by yxztj** [comment]
Yeah as we expected Apple is not replying on radar. Maybe we can find a workaround? @appleguy

**Comment by appleguy** [comment]
@yxztj thanks again for your patience - we're getting closer to being able to investigate this.  Curious if you've tried with the new optimized sizing + display codepaths.  One PR still hasn't been merged (see the one from Adlai about drawing fast path), but the sizing fast path may actually fix this in cases that don't use a custom .truncationAttributedString (which is the common case).

**Comment by yxztj** [comment]
@appleguy I just tested with latest master(commit: 4dca05767bf7f5d555746d8cb9e444de51bd458b) in the demo project, the issue is still there(no matter truncationAttributedString is set) :(

**Comment by appleguy** [comment]
@Adlai-Holler - since you looked at ASTextNode recently, do the symptoms described here sound familiar in any sense?

@yxztj Thanks for your patience!  We are almost done adopting all of the 2.0 APIs in Pinterest, so we should be able to investigate this in the next couple weeks.

**Comment by maicki** [comment]
@Adlai-Holler @appleguy Just looked into that a bit with master. So apparently this works now reliable, unfortunately reliable wrong. Setting the `maximumNumberOfLines` to 3 (no matter truncationAttributedString is set) the text node will show only 2 lines of text but the text node is in fact the right size.

![screen shot 2016-11-08 at 9 55 48 am](https://cloud.githubusercontent.com/assets/25288/20110514/880d4468-a599-11e6-87fa-9fabaffb03c8.png)

**Comment by appleguy** [comment]
@yxztj quick update here.  The team is now focused on ASTextNode improvements.  @maicki did a variety of investigation here, and @Adlai-Holler has been working on some significant changes to address an issue discovered in the truncation algorithm.

It will be some difficult work, but we currently expect to have this issue fixed in the next couple weeks.  We are sprinting to try to have it addressed for the Dec 1st event.  Feel free to discuss with Adlai on Slack (note however he is currently working from Japan timezone)

**Comment by yxztj** [comment]
@appleguy Just tested with 2.0 release. The issue is still there..

**Comment by yxztj** [comment]
@maicki @Adlai-Holler Not sure if #2643 is related, but the PR didn't fix this issue. Tested with latest master branch.

**Comment by bawn** [comment]
+1

**Comment by yxztj** [comment]
@appleguy @hannahmbanana Happy new year! Sorry to ping you again but not being able to truncate text with line spacing has been bothering us for over half a year. I know it involves some major improvements in the whole async text rendering/layout process, and that's why we weren't trying to fix it ourselves.

Do you think we can get a workaround soon? Or maybe currently I could use ASDisplayView to wrap a UILabel instead?

**Comment by stevenojo** [comment]
I'm seeing a similar issue in my project with ASTextNode. Not sure if they are realted, but figured it might be worth commenting here: 

With custom lineSpacing of 8 on the attributed string, when I set maximumNumberOfLines = 2, I'm only seeing one line displayed on certain strings that are 3 or 4 lines. Compare the difference in the "National Lampoon.." with these two settings, and note the "All Dogs Go To Heaven" TextNode being unaffected. 



When maximumNumberOfLines is set to 0 (default): 
<img width="374" alt="screen shot 2017-02-02 at 5 29 02 pm" src="https://cloud.githubusercontent.com/assets/583768/22575921/8ea3f214-e96d-11e6-9f61-925238480d0f.png">

With maximumNumberOfLinesSet to 2: 
<img width="379" alt="screen shot 2017-02-02 at 5 30 23 pm" src="https://cloud.githubusercontent.com/assets/583768/22575962/bb8be642-e96d-11e6-85b6-0d3c7be93236.png">

The expectation, is that the ASTextNode would truncate text on the second line. Is there a workaround for this, or a fix I could make that could resolve this?

**Comment by stevenojo** [comment]
Found a workaround for my own issue:

In my case it was as simple as changing `truncationMode` to `.byTruncatingTail` instead of the default option and the problem ceased. Does that work for anyone else by chance?

**Comment by Shafichariri** [comment]
Hi, Any updates on this issue?

**Comment by xilin** [comment]
@stevenojo Thanks for the tip, it works for me.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#140
